#!/bin/bash

#
# dotdeploy - dispatcher script
# 
# 
SCRIPT_NAME=$(echo $0 | rev | cut -d/ -f1 | rev)
DOTDEPLOY_DIRECTORY="$HOME/.dotdeploy"

function print_usage {
    if [ -n "$1" ]
    then
        echo ERROR: $1
        echo
    fi
 
    echo -e "\e[01;1mdotdeploy v0.1\e[00m
    
Usage:
    $SCRIPT_NAME \e[01;1m<command> [arguments...]\e[00m 
  
Description:
    See http://dotdeploy.works
  
Commands: 
    $SCRIPT_NAME \e[01;1mhelp\e[00m - Displays $0 help.
    $SCRIPT_NAME \e[01;1madd <filename> [profile]\e[00m - Adds a file for remote tracking.
    $SCRIPT_NAME \e[01;1mupdate\e[00m  - Updates all files.. 
    $SCRIPT_NAME \e[01;1mstatus [filename]\e[00m  - Prints tracking status of this machine or file. 
    $SCRIPT_NAME \e[01;1muninstall\e[00m - Stops tracking this machine and restores original files.
    $SCRIPT_NAME \e[01;1mname\e[00m (implement?)"
}


## check that dotdeploy files are correctly setup
if [ ! -d $DOTDEPLOY_DIRECTORY/lib ] 
then
    print_usage 
    echo
    echo -e "\e[01;31m[error]\e[00m - dotdeploy is not installed in $HOME. Please visit http://dotdeploy.works for installation instructions."
    exit 1
fi 

## now that we know dotdeploy is instaled, proceed. 
## note somebody could nefariously put a .sh file and it will get sourced automatically this way.
source $DOTDEPLOY_DIRECTORY/lib/*.sh

# todo spencer ensure that the command was supported and valid
command=$1

#if [[ $command == "" ]] 
#then 
  #  $command="help"
#fi
   
case "$command" in
    ''|help)
        print_usage
        ;;
    
    add)
        echo "not implemented"
        ;;
        
    update)
        echo "not implemented"
        ;;
    
    status)
        echo "not implemented"
        ;;
        
    uninstall)
        echo "not implemented"
        ;;
        
    name)
        echo "not implemented"
        ;;
esac
